### ISSUE TITLE
Reverse dependencies

### ISSUE THREAD

**Issue by maelle** [r-hub/crandb#48]
* [`cranatgh`](https://github.com/metacran/cranatgh)

* probably other R-hub/METACRAN stuff?

**Comment by gaborcsardi** [comment]
Everything relies on the web service, not on the R package.

**Comment by maelle** [comment]
ok so not too much to worry about when merging this into `pkgsearch` then?

**Comment by gaborcsardi** [comment]
Well, the R package is (also) used to update the web service, but yeah.

**Comment by maelle** [comment]
Ok, where's the code for that? to keep a note to update it.

**Comment by gaborcsardi** [comment]
In our CI.

**Comment by gaborcsardi** [comment]
It is here: https://github.com/metacran/cron/blob/master/minutely/update-crandb.r

**Comment by maelle** [comment]
using internal functions! thanks for the link
